[build]
publish = "frontend"
functions = "netlify/functions"

[[redirects]]
from = "/"
to = "/pages/index.html"
status = 200

[[redirects]]
from = "/student"
to = "/pages/student.html"
status = 200

[[redirects]]
from = "/admin"
to = "/pages/admin.html"
status = 200

[[redirects]]
from = "/delivery"
to = "/pages/delivery.html"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/backend-proxy?path=:splat"
status = 200
force = true

[[redirects]]
from = "/uploads/*"
to = "/.netlify/functions/backend-proxy?path=uploads/:splat"
status = 200
force = true
